import { defineField, defineType } from "sanity";
import { AsideStyle } from "../components/AsideStyle";

export default defineType({
  name: "post",
  title: "Blog Post",
  type: "document",
  fieldsets: [
    {
      name: "seo",
      title: "SEO & AEO",
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      to: { type: "author" },
    }),
    defineField({
      name: "mainImage",
      title: "Main Image",
      type: "image",
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      of: [{ type: "reference", to: { type: "category" } }],
    }),
    defineField({
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
      description: "Set to now by default. Clear to save as draft.",
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "featuredVideo",
      title: "Featured Video",
      type: "reference",
      to: { type: "video" },
      description: "Optional: Attach a video to this post",
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [
        {
          type: "block",
          // Declaring styles replaces Sanity's defaults, so the built-ins we
          // still want are listed explicitly. H1 stays available for existing
          // content, but the article template renders it as an h2 so each page
          // keeps a single h1.
          styles: [
            { title: "Normal", value: "normal" },
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Quote", value: "blockquote" },
            {
              title: "Aside",
              value: "aside",
              component: AsideStyle,
            },
          ],
        },
        {
          type: "image",
          options: { hotspot: true },
        },
      ],
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      initialValue: false,
      description: "Mark this post as featured on the blog page",
    }),
    defineField({
      name: "notificationSent",
      title: "Notification Sent",
      type: "boolean",
      initialValue: false,
      description: "Has the email notification been sent for this post?",
      readOnly: true,
    }),
    // SEO & AEO Fields
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      fieldset: "seo",
      description: "SEO-optimized title (50-60 characters)",
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
      fieldset: "seo",
      description: "Meta description for search results (150-160 characters)",
      validation: (Rule) => Rule.max(170),
    }),
    defineField({
      name: "primaryKeyword",
      title: "Primary Keyword",
      type: "string",
      fieldset: "seo",
      description: "Main target keyword for this post",
    }),
    defineField({
      name: "secondaryKeywords",
      title: "Secondary Keywords",
      type: "array",
      of: [{ type: "string" }],
      fieldset: "seo",
      description: "Additional target keywords",
    }),
    defineField({
      name: "ogImage",
      title: "OpenGraph Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "seo",
      description: "Dedicated OG image (1200x630). Falls back to main image.",
    }),
    defineField({
      name: "schemaMarkup",
      title: "Schema Markup (JSON-LD)",
      type: "text",
      rows: 10,
      fieldset: "seo",
      description: "Structured data as JSON-LD. Auto-generated by the SEO optimizer.",
    }),
  ],
  preview: {
    select: {
      title: "title",
      author: "author.name",
      media: "mainImage",
    },
    prepare(selection) {
      const { author } = selection;
      return { ...selection, subtitle: author && `by ${author}` };
    },
  },
});

